//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOgrenciDers
    {
        public int ogrenciID { get; set; }
        public string dersID { get; set; }
        public int yil { get; set; }
        public int yariyil { get; set; }
    
        public virtual tDers tDers { get; set; }
        public virtual tOgrenci tOgrenci { get; set; }
    }
}
