//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOgrenci
    {
        public int ogrenciID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string bolumID { get; set; }
    
        public virtual tBolum tBolum { get; set; }
        public virtual tOgrenciDers tOgrenciDers { get; set; }
    }
}
